import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="md:mx-12 2xl:container 2xl:mx-auto"> {/*** Custom Container applied from md with mx-12 ***/}
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
